name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag maxking/mailman-ci-runner:latest
    - name: DockerHub login
      run: docker login -u="maxking" -p="{{ secrets.CI_JOB_TOKEN }}"
    - name: Push the Docker image
      run: docker push maxking/mailman-ci-runner:latest
