name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/maxking/mailman-ci-runner:latest
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CI_JOB_TOKEN }}
    - name: Push the Docker image
      run: docker push ghcr.io/maxking/mailman-ci-runner:latest
